ingressController:
  enabled: false

image:
  repository: kong
  tag: "3.7"

secretVolumes:
  - kong-cluster-cert   # same TLS secret you created for CP

env:
  role: data_plane
  database: "off"   # DP is DB-less

  # Control Plane endpoints (created by the CP release)
  cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  cluster_telemetry_endpoint: kong-cp-kong-clustertelemetry.kong.svc.cluster.local:8006

  # Trust & present our shared cert
  lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key

# Expose the DP proxy so you can hit it from your host
proxy:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 80
    nodePort: 32080    # we mapped this from the k3d server to your host
  tls:
    enabled: false

admin:
  enabled: false
manager:
  enabled: false

enterprise:
  enabled: false
